FotoBlog-24-01-2024/Models/ErrorViewModel.cs
namespace FotoBlog_24_01_2024.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FotoBlog-24-01-2024/Models/YeniGonderiViewModel.cs
using FotoBlog_24_01_2024.Attributes;
using System.ComponentModel.DataAnnotations;

namespace FotoBlog_24_01_2024.Models
{
    public class YeniGonderiViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Başlık")]
        [Required(ErrorMessage = "{0} girilmesi zorunludur!")]
        public string Baslik { get; set; } = null!;


        [Display(Name = "ResimYolu")]
        [Required(ErrorMessage = "{0} koyulması zorunludur!")]
        [GecerliResim(MaxDosyaBoyutuMb =1.2)]
        public IFormFile Resim { get; set; } = null!;
    }
}

FotoBlog-24-01-2024/Controllers/GonderilerController.cs
using FotoBlog_24_01_2024.Data;
using FotoBlog_24_01_2024.Models;
using Microsoft.AspNetCore.Mvc;

namespace FotoBlog_24_01_2024.Controllers
{
    public class GonderilerController : Controller
    {
        private UygulamaDbContext _db;
        private IWebHostEnvironment _env;

        public GonderilerController(UygulamaDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(YeniGonderiViewModel yeniGonderiViewModel)
        {
            if (ModelState.IsValid)
            {
                //işlem
                string ext = Path.GetExtension(yeniGonderiViewModel.Resim.FileName);
                string yeniDosyaAd = Guid.NewGuid() + ext;
                string yol = Path.Combine(_env.WebRootPath, "img", "upload", yeniDosyaAd);

                using (var fs = new FileStream(yol, FileMode.CreateNew))
                {
                    yeniGonderiViewModel.Resim.CopyTo(fs);
                }
                _db.Gonderiler.Add(new Gonderi
                {
                    Baslik = yeniGonderiViewModel.Baslik,
                    ResimYolu = yeniDosyaAd
                });
                _db.SaveChanges();
                return RedirectToAction("Index", "Home", new { Sonuc = "Eklendi" });
            }

            return View();
        }
    }
}

FotoBlog-24-01-2024/Controllers/HomeController.cs
using FotoBlog_24_01_2024.Data;
using FotoBlog_24_01_2024.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FotoBlog_24_01_2024.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UygulamaDbContext _db;
        public HomeController(ILogger<HomeController> logger,UygulamaDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Gonderiler
                .OrderByDescending(x=>x.Id)
                .ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FotoBlog-24-01-2024/Views/Gonderiler/Yeni.cshtml
@model YeniGonderiViewModel
@{
    ViewData["Title"] = "Yeni Gönderi Ekle";
}
<h2> @ViewData["Title"]</h2>

<form method="post" enctype="multipart/form-data" asp-action="Yeni">
    <div class="mb-3">
        <label class="form-label" asp-for="Baslik"> Başlık </label>
        <input type="text" asp-for="Baslik" class="form-control" />
        <span asp-validation-for="Baslik" class="text-danger"> </span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Resim">  </label>
        <input type="form-control" type="file" asp-for="Resim" />
        <span asp-validation-for="Resim" class="text-danger mt-1"> </span>
    </div>
    <button class="btn btn-primary" >Ekle</button>

</form>

FotoBlog-24-01-2024/Views/Home/Index.cshtml
@model List<Gonderi>

@{
    ViewData["Title"] = "Home Page";
}


<div class="gonderiler">
    @if (Context.Request.Query["Sonuc"] == "Eklendi")
    {
        <div class="alert alert-success">
            Gönderi başarıyla oluşturuldu.

        </div>
    }
    <div class="d-flex">
        <a asp-action="Yeni" asp-controller="Gonderiler" class="btn btn-dark ms-auto"> Yeni Gönderi Ekle  </a>
    </div>

    @foreach (Gonderi a in Model)
    {
        <div class="mb-4">
            <h4> @a.Baslik</h4>
            <img class="w-100" src="~/img/upload/@a.ResimYolu" />
        </div>
    }
</div>

FotoBlog-24-01-2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FotoBlog_24_01_2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FotoBlog_24_01_2024.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FotoBlog_24_01_2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FotoBlog_24_01_2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>